/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface ClueExplanations {
  answer: string;
  clue_number: number;
  clue_text: string;
  created_at: Generated<string | null>;
  direction: string;
  explanation_json: string;
  id: Generated<number>;
  puzzle_id: number;
}

export interface ExplanationBatches {
  applied_at: string | null;
  batch_id: string;
  created_at: Generated<string | null>;
  id: Generated<number>;
  input_file_id: string;
  output_file_id: string | null;
  puzzle_id: number;
  status: string;
  updated_at: Generated<string | null>;
}

export interface ExplanationRegenerations {
  answer: string;
  clue_text: string;
  created_at: Generated<string | null>;
  error_message: string | null;
  explanation_json: string | null;
  feedback: string | null;
  previous_explanation_json: string | null;
  request_id: string | null;
  status: Generated<string>;
  updated_at: Generated<string | null>;
}

export interface ExplanationReports {
  anonymous_id: string | null;
  clue_number: number;
  direction: string;
  explanation_updated: Generated<number>;
  feedback: string | null;
  id: Generated<number>;
  puzzle_id: number;
  reported_at: Generated<string | null>;
  user_id: number | null;
}

export interface Friendships {
  created_at: Generated<string>;
  id: Generated<number>;
  requested_by: number;
  status: Generated<string>;
  updated_at: Generated<string>;
  user_id_1: number;
  user_id_2: number;
}

export interface ParsewordsPuzzles {
  clue_number: number;
  created_at: Generated<string | null>;
  direction: string;
  id: Generated<number>;
  puzzle_id: number;
  puzzle_json: string;
  updated_at: Generated<string | null>;
}

export interface Puzzles {
  answers_encrypted: string | null;
  book: string | null;
  clues: string;
  grid: string;
  id: Generated<number>;
  is_published: Generated<number>;
  letter_count: number | null;
  puzzle_number: number | null;
  title: string;
}

export interface PuzzleSessions {
  anonymous_id: string | null;
  attributions: Generated<string | null>;
  created_at: string | null;
  is_complete: Generated<number | null>;
  puzzle_id: number;
  session_id: string | null;
  state: string;
  updated_at: string | null;
  user_id: number | null;
}

export interface SessionPushSubscriptions {
  auth: string;
  created_at: Generated<string | null>;
  endpoint: string;
  id: Generated<number>;
  last_notified_at: string | null;
  p256dh: string;
  session_id: string;
  user_id: number;
}

export interface Users {
  created_at: Generated<string>;
  id: Generated<number>;
  is_admin: Generated<number>;
  password_hash: string;
  updated_at: Generated<string>;
  username: string;
}

export interface DB {
  clue_explanations: ClueExplanations;
  explanation_batches: ExplanationBatches;
  explanation_regenerations: ExplanationRegenerations;
  explanation_reports: ExplanationReports;
  friendships: Friendships;
  parsewords_puzzles: ParsewordsPuzzles;
  puzzle_sessions: PuzzleSessions;
  puzzles: Puzzles;
  session_push_subscriptions: SessionPushSubscriptions;
  users: Users;
}
