import db from './db-knex'

const newPuzzles = [
  {
    id: 6,
    title: "21",
    grid: "B B N W N W N W N W N W N W B\nN B W B W B W B W B W B W B B\nN W W W W W W W B N W W W W N\nW B W B W B W B W B W B W B W\nN W W W W W W W W B N W W W W\nW B W B W B W B W B N B W B W\nN W W W W W W N B N W W W W W\nW B B B W B N W N B W B B B W\nN W N W W W B N W W W W N W W\nW B W B W B N B W B W B W B W\nN W W W B N W W W W W W W W W\nW B W B N B W B W B W B W B W\nN W W W W W W B N W W W W W W\nB B W B W B W B W B W B W B B\nB N W W W W W W W W W W W B B",
    clues: "{\"across\":[{\"number\":1,\"clue\":\"Money in RC education sadly not in everyone's interest (12)\"},{\"number\":8,\"clue\":\"Ten red tailless oxen surprisingly reproduced (7)\"},{\"number\":9,\"clue\":\"Payment for student at uni with dreadful mumps (4,3)\"},{\"number\":11,\"clue\":\"Able to change direction, River Elbe wanders across south (10)\"},{\"number\":12,\"clue\":\"East European's small loo (4)\"},{\"number\":14,\"clue\":\"Six tours arranged round Ohio for top musician (8)\"},{\"number\":16,\"clue\":\"Number engaged in endless pastime rub shoulders (6)\"},{\"number\":17,\"clue\":\"Your old smithy's half disappeared (3)\"},{\"number\":19,\"clue\":\"Ball at Lord's associated with Internet company? (6)\"},{\"number\":21,\"clue\":\"Learn writer is in Rome, working (8)\"},{\"number\":24,\"clue\":\"College returned fiver, say (4)\"},{\"number\":25,\"clue\":\"Where MPs stay to protect their chamber? (10)\"},{\"number\":27,\"clue\":\"I'm implicated in poor sales, not having a target (7)\"},{\"number\":28,\"clue\":\"Lines up broadcast in store (7)\"},{\"number\":29,\"clue\":\"Coe simply arranged to hold special AGM to stage them? (7,5)\"}],\"down\":[{\"number\":1,\"clue\":\"Silly supervisor sent out SOS heading away from the sea (7)\"},{\"number\":2,\"clue\":\"Roux cooked with style under duke, showing skill (10)\"},{\"number\":3,\"clue\":\"The most filthy must have died horribly (8)\"},{\"number\":4,\"clue\":\"Heartless Lord and Lady support firm without warmth (6)\"},{\"number\":5,\"clue\":\"Mary has to be trained to join it (4)\"},{\"number\":6,\"clue\":\"Help for diabetic at home follows endless affront (7)\"},{\"number\":7,\"clue\":\"Additional vehicle tours Georgia and S. Africa in big show (12)\"},{\"number\":10,\"clue\":\"Lamb's feet cooked over eggs for Easter, say (7,5)\"},{\"number\":13,\"clue\":\"Form of religion cultivated in most homes nearly (10)\"},{\"number\":15,\"clue\":\"Not much resistance from old monarch (3)\"},{\"number\":18,\"clue\":\"Layer spread on top of ground for all of 12 months (8)\"},{\"number\":20,\"clue\":\"The best gemstone Tim brought in (7)\"},{\"number\":22,\"clue\":\"A sign displayed around centre of Guam: 'Reptiles!' (7)\"},{\"number\":23,\"clue\":\"Smile wryly eating posh breakfast (6)\"},{\"number\":26,\"clue\":\"Mineral layer in deep mass (4)\"}]}",
  },
  {
    id: 7,
    title: "22",
    grid: "B B N W N W N W N W N W N W B\nN B W B W B W B W B W B W B B\nN W W W W W W W B N W W W W N\nW B W B W B W B W B W B W B W\nN W W W W W W W W B N W W W W\nW B W B W B W B W B N B W B W\nN W W W W W W N B N W W W W W\nW B B B W B N W N B W B B B W\nN W N W W W B N W W W W N W W\nW B W B W B N B W B W B W B W\nN W W W B N W W W W W W W W W\nW B W B N B W B W B W B W B W\nN W W W W W W B N W W W W W W\nB B W B W B W B W B W B W B B\nB N W W W W W W W W W W W B B",
    clues: "{\"across\":[{\"number\":1,\"clue\":\"Maybe celibacy inspires church in what makes wheels turn? (7,5)\"},{\"number\":8,\"clue\":\"Crime of person who sells stolen goods (7)\"},{\"number\":9,\"clue\":\"A prune stupidly claims victory for upstart (7)\"},{\"number\":11,\"clue\":\"Grant independence to docile ones abroad (10)\"},{\"number\":12,\"clue\":\"Where guys are tense and effeminate (4)\"},{\"number\":14,\"clue\":\"One French student's shocking, breaking rules (8)\"},{\"number\":16,\"clue\":\"A group of boys terrifies very shy person (6)\"},{\"number\":17,\"clue\":\"One hand – two of them to produce fruit (3)\"},{\"number\":19,\"clue\":\"What's the point of relocating job etc? (6)\"},{\"number\":21,\"clue\":\"Musical baggage-handler? (8)\"},{\"number\":24,\"clue\":\"Indian ruler's open, laid back (4)\"},{\"number\":25,\"clue\":\"It'd be a calamity if men's tour gets rescheduled (10)\"},{\"number\":27,\"clue\":\"Take away tarted up with bit of caramel (7)\"},{\"number\":28,\"clue\":\"Substitute thick cloth with much finer material (7)\"},{\"number\":29,\"clue\":\"Henry's rum and rye blend - ideal to put kids to sleep (7,5)\"}],\"down\":[{\"number\":1,\"clue\":\"Twisted optical fibres priest rejected for this lens (7)\"},{\"number\":2,\"clue\":\"Warm tufted fabric that burns slowly (10)\"},{\"number\":3,\"clue\":\"Makes tidy profits to a large extent (6,2)\"},{\"number\":4,\"clue\":\"Reveal name of biggest show in Kent perhaps? (6)\"},{\"number\":5,\"clue\":\"Listen, old boat's at rear of harbour (4)\"},{\"number\":6,\"clue\":\"Approximate distribution of tax in EC (7)\"},{\"number\":7,\"clue\":\"Cheerful but rough mood due to be dispelled (4-8)\"},{\"number\":10,\"clue\":\"In a class of its own but out of alignment? (12)\"},{\"number\":13,\"clue\":\"Happy? Go and try complex art of men of letters (10)\"},{\"number\":15,\"clue\":\"I hear there's a shortage of resinous substance (3)\"},{\"number\":18,\"clue\":\"Traveller's very much finer, it's said (8)\"},{\"number\":20,\"clue\":\"Fetish in Africa keeps its system of self-defence (2-5)\"},{\"number\":22,\"clue\":\"Frankfurter man of wisdom tours the States (7)\"},{\"number\":23,\"clue\":\"Rare marsh bird's not quite freezing (6)\"},{\"number\":26,\"clue\":\"They eat moths and bananas (4)\"}]}",
  }
]

const importPuzzles = async () => {
  for (const puzzle of newPuzzles) {
    await db('puzzles').insert({ title: puzzle.title, grid: puzzle.grid, clues: puzzle.clues })
  }
}

importPuzzles().then(() => {
  process.exit(0)
})
